#! /bin/sh

# Killing any possible previous processes
killall -q -w picom
killall -q -w sxhkd
killall -q -w polybar

#auto start
sxhkd &
pactl set-sink-volume @DEFAULT_SINK@ 15%
picom &
fcotx -d &
unclutter & 
sh .config/polybar/launch.sh &
feh --bg-scale --randomize ~/wallpapers &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
